#set text(font:"Open Sans", size:11pt, hyphenate: false)
#set page(numbering:"1")
#set par(justify: true, leading: 1.5em)
#set heading(numbering: "1.1")
#show math.equation.where(block: false): box
#set math.equation(numbering: "(1)")

#let fill(txt) = underline(text(red, weight: "bold")[FILL #txt])
#let check(txt) = underline(text(blue, weight: "bold")[CHECK #txt])
#let cite = underline(text(green, weight: "bold")[CITE HERE])

#import "@preview/simple-plot:0.3.0" : plot

#import "@preview/lets-go:0.1.0": go-board, go-board-9
#import "@preview/algorithmic:1.0.7"
#let AE=("left","bottom","right","top")

#place(
  top + center,
  scope: "parent",
  float: true,
  text(1.4em, weight: "bold")[
    Dynamic Adjustment of Monte Carlo Tree Search #linebreak() Simulations for a
    9 #math.times 9-Go-AI
  ],
)

#let max_number=300

#outline()

#pagebreak()
= Introduction
Creating a machine that is capable of playing games has been a
fascination to
humanity @mechanical_turk and an integral part of
Computer Science @turochamp for a long time. It is a benchmark to human 
intelligence and
an exploration of the boundaries of what is capable using
artificial decision making. This culminated in the defeat of reigning world-chess
champion, Garry Kasparov, at the computations of the IBM chess computer DeepBlue
in 1997 @kasparov_v_deep_blue.
This spurred on further improvement on chess machines that is still ongoing
@stockfish_blog and research on a
multitude of other games. 
One such game is the popular game by the name of Go. It remained a unbeaten challenge to
scientists for 19 more years @sedol_v_alphago. While many approaches were tested, it was not
until 2016 that, on equal footing, a
high-ranking professional player was beaten by Google-DeepMind's artificial
intelligence (AI), AlphaGo. AlphaGo used a vastly different approach from earlier
game computers and programs @alphago. It combined Deep Neural Network (DNN) training with
exploration guided by distributions output by the neural network. #cite


== Problem
One issue that is apparent with most AIs is the amount of ressources that is
necessary for training as well as for their subsequent deployment @aireport. Literature
and the news are abundant with ever-growing models with needs for more and
better hard-ware and energy.
While improving AI's capability in all domains is an important 
important pursuit to stretch
the limits of what is possible, it is also important to lower the costs of
operating such machines. In particular, algorithms that make use of Monte Carlo Tree
Search (MCTS), as in the case of AlphaGo @alphago and its successors like
AlphaGo Zero
@alphagozero, seem to execute a lot of 
unnecessary
computation because base MCTS executes a set number of simulations without
consideration to whether all of these simulations are necessary.

== Hypothesis
The central claim of this thesis is that efficiency of MCTS with predictors can
be increased by
dynamically adjusting the amount of simulations based on heuristics that make
use
probabilties generated by the predictor while upholding the same level of
performance. 
The development and implementation of such predictive heuristics are the goal of this 
thesis.



= Background knowledge
== Go
Go is a Chinese board game that has a history spanning more than 4,000 years.  It is
played by two-players using black and white stones. While usually played on a 19
#math.times 19-grid, other board sizes like 9 #math.times 9 or 13 #math.times 13
are also common. 
The goal of the game is to enclose more territory, meaning, grid
intersections, than the opponent.

The players place stones in turn; the player with the black stones begins. The
group of free places around a single stone are called liberties, see @liberties. 
Stones of the same colour that are placed on neighbouring fields are considered
a group and share the liberties. A group may be arbitrarily large. A
group of the opponent can be captured by filling in all liberties of the
group, see @capturing. While generally any stone may be placed anywhere on the
board, it may not be placed in places where the stone or its group dies because
of the stone having been placed. The exception is if the stone is the cause for
a successful capture of the opponent's stones. Importantly, a board position may
not be immediately repeated. This means,
after a stone has been captured, the capturing stone may not be recaptured
on the next move.
This is called Ko.

#figure(
  placement: top,
  columns(2)[
    #figure(
      kind: "subfigure", supplement: "Figure",
      block(width: 5em, go-board(
        size: 3,
        stones: ("bb",),
        marks: ("ab","ba","bc","cb"),
        mark-radius: 7%,
        open-edges: AE,
        open-edges-added-length: 7%,
      )),
      caption: [Liberties of stones],
    ) <liberties>
    #colbreak()
    #figure(
      {
        block(width: 5em, go-board(
          size: 3,
          stones: ("ab", "bb", "ba", "bb", "bc"),
          marks: ("cb",),
          mark-radius: 7%,
          open-edges: AE,
          open-edges-added-length: 7%,
        ))
      },
      caption: [Capturing a Stone],
    ) <capturing>
  ],
)

The game ends when both players pass consecutively, typically when all
meaningful moves have been played and the territories are settled.
Once play is concluded, the territory is counted.
Unoccpied grid intersections within their territory each correspond to each
point for the respective
player. Captured stones each represent additional points for the player who
captured them. Captured stones that remain on the board while counting are worth
two points for the occupied field and the stone itself.

To compensate black's advantage in going first and avoid draw, additional
5.5-7.5 points are awarded to white. This is called komi.
Komi can be adjusted to even out the differences in capability
between inequally strong players. Lastly, komi can be combined with a handicap
that places black stones on predetermined spots on the board.

Traditionally, players, human or computational, are attributed ranks based on 
strength. Beginners' ranks start at 30 kyu. The limit 1 
kyu. After reaching 1 kyu, players can reach rankings from 1 dan to 9 dan. 
Professional players are ranked 
separately with their own dan-scale. Nowadays, players are also evaluated using
the Elo-system.


= Technical Background

== Reinforcement Learning and Self-Play
Reinforcement Learning (RL) describes a Machine Learning (ML) paradigm in which
an agent is trained to maximize a reward signal in interaction with its
environment @rl_intro.
Generally during training, an agent makes use of two concepts called
exploitation and exploration. On one side, to exploit
is to choose a path of action that is known to produce a good result. On the
other side, to explore is to choose a path of action that is not well-known and
thus, upon further examination, may produce a better result than already known
paths of action.

Self-play is a training scheme within the field of RL @alphagozero. In self-play, an
algorithm competes against an earlier iteration of itself. In the scenario of
this paper, a training version plays a match of Go against a previous iteration
of itself. In this sense, 
the previous iteration is part of the environment and the reward signal is
the outcome of the match. Various selection strategies exist for the
iteration against which is played, for example, a random iteration is chosen to
play, or the
selection follows a "King-of-the-Hill"-approach, where the strongest iteration
remains as the benchmark and is to be beaten. This, more than the randomised
selection shows growth in performance of the agent.


== Deep Neural Networks

=== Artificial Neural Networks
Today, artificial neural networks (ANN) are one of the most used and researched
technologies. With their groundwork laid in 1958 @perc_rosenblatt, new methods 
have been since
been developed for a large number of purposes, not the least of which is playing
games and improving beyond human capabilities.

Generally, ANNs receive an input of arbitrary format, defined per usecase.
During the forward pass, the
signal of 
this input are propagated through the network to the output layer @backprop. One layer is
made up of multiple neurons, each with its own weights per input, plus a bias
individual to each neuron. In the 
context to RL, the ANN's output is evaluated for its reward signal in response 
to the environment. From this, an error signal is generated and passed backwards 
through the network. Each layer is updated dependent on the succeeding layer's,
that is in the direction of the forward pass,
error signal.


=== Residual Neural Networks
In the course of research and development of ANNs, they have grown exponentially
deeper. Beginning with a single perceptron, which were then used in a single 
layers, now, there are networks using neurons with more than 100 layers and a 
large number of perceptrons per layer. Users of ANNs of this size noticed the 
problem of the Vanishing Gradient @resnet. In the process of backpropagation, the 
derivatives' chain rule is employed. For that, multiple small decimal numbers
are repeatedly multiplied. This produces even smaller decimal numbers
The Vanishing Gradient describes the phenomenon that the error signal
that early layers of the networks receive is too small to effectively change the
weights and biases of those layers. This stops learning from having any effect.

To solve this problem, residual neural networks (ResNet) were introduced in Deep Learning
(DL) problems. ResNet's make use of  "skipping
connections" @resnet. In one of connection, a residual layer projects its output not only to the
succeeading layer but also to 
another
layer further down the stack of layers, skipping the layers inbetween. The
residual output is added to the output of the layer, to which it is is
projected.
This largely
fixes the Vanishing Gradient since the output of the layer is passed further
into the stack of layers. 

A negative point in this setup is that the intermediate layers may be found to
be superfluous and converge to $0$ during training.

=== Convolutional Neural Networks
Most objects depend on their multi-dimensional structure to be considered when
analysing them. Images, for example, rely on the spatial position of pixels in
relation to one another in order to correctly depict objects. Humans make use of
layered groups of neurons with distinct tasks to recognise groups of features
and form an understanding of objects from them.


Computationally, this structure is approximated using Convolutional Neural
Networks (CNN). Similarly to their biological counterparts, CNNs find
substructures that are common for multiple objects in early layers @cnn. Combining
these features in later layers enables recognition of more specific types of
objects.
In a convolutional layer, kernels, that is, tensors, operate on a
receptive field of inputs to generate outputs by sliding over the input making the
operation translationally invariant instead of operating on the whole input at
the same time. The weights in
these layers can be learned through training.

#linebreak()

Go, being a board game that played in two-dimensions, is especially well-suited to 
being
analysed using CNNs. Much like recognising an object, local situations such as
fights or life-and-death can be
analysed in early layers and evaluated within the global context of the match in
later layers. For proper recognition and evaluation of local and global
situations, Go requires deep insight of the board. For more accurate
representations of the global position, the combination with ResNets becomes
vital to sustain trainability.



== Monte Carlo Tree Search
MCTS is a versatile heuristic decision making algorithm. During the search, a 
tree is
built based on the original state represented by root node $R$. Every child node
$i$ of $R$ is a new board position, in which a different move $a_i$ was played.
Through exploration of subsequent
state from $R$, MCTS finds a state that is most likely to maximise a
metric that can be changed per use-case. 
Every node $i$ of the tree keeps track of how many simulations made use of $i$,
$n_i$, and how many simulations are considered wins, $w_i$.
There are four stages to MCTS:
+ Selection: From $R$, choose a child node according to a selection
  method.
  Repeat until choosing a leaf node $C$.
+ Expansion: If $C$ is not a terminal state, meaning, there is a possible following
  state, create new child nodes. Choose a new child state $S$.
+ Evaluation #footnote[This step is also called simulation. For the sake of
  clarity within the scope of this thesis, "evaluation" will be used for this step
  of the process.]: Evaluate $S$. $S$ may be evaluated by choosing random 
  subsequent states
  until a terminal state which has a definitive value. Another method is an
  evaluation function applied to $S$.
+ Backpropagation: Update the visit and win counts in the path from $S$ to $R$
  under consideration of
  the result from the evaluation.
Through rigorous exploration of the tree by simulations, meaning, paths from root
to terminal nodes, the child states most likely to maximise the evaluation
method are expected to converge to higher values in the selection method.

The selection method commonly used in the selection phase is the "Upper
Confidence Bound 1 applied to Trees" (UCT) @uct. It is used to find a balance
between exploitation of well-simulated moves and exploration of under-explored
moves in MCTS.
In the selection stage, node $i$ with the highest value according to the
expression
$ Q(s,a_i) + U(s,a_i) = w_i/n_i + c sqrt((ln N_i) / n_i) $
is selected, where 
- $Q(s,a) = w_i/n_i$ is a measure of how good $a_i$ is in state $s$, 
- $U(s,a) = sqrt((ln N_i) / n_i)$ is a measure of how well explored move $a_i$ is,
- $w_i$ is the number of wins that the successor states of $s$ accumulate if
  $a_i$
  is played,
- $n_i$ is the number of times that $a_i$ was chosen during the simulations,
- $N_i$ is the number of times that $s$ was part of the simulations,
- $c$ is an exploration parameter. The higher the more explorative the move
  selection is.
Since $sqrt((ln N_i)/n_i) approx infinity$, every move is tried out at least
once.

=== Probabilistic Upper Confidence Bound applied to Trees
The Probabilistic Upper Confidence Bound applied to Trees (PUCT) is a variant of
UCT that incorporates prior estimations on the goodness of the actions of a state
@alphagozero.
These evaluations are typically provided
by predictors like a neural network or a domain-specific heuristics.

It uses a different uncertainty calculation:
$ U(s,a)=c_"puct" dot P(s,a) dot sqrt(N_i)/(1+n_i), $
where 
- $c_"puct"$ is a constant that guides the level of exploration and
- $P(s,a_i)$ is the evaluation of move $a_i$ in state $s$ according to the
  predictor.

A fundamental change is that
$sqrt((ln N_i) / n_i) != sqrt(N_i)/(1+n_i)$ because it is
accepted that not every possible move in $s$ is tried out. Furthermore,
$ln(N_i)$ asymptotically approaches a maximum, in comparison, $sqrt(N_i)$ keeps
growing.

== Kendall Rank Correlation Coefficient
The Kendall Rank Correlation Coefficient (KRCC) is a tool to
calculate the similarity of the same type of objects @rankcorrelation. 
In the context of this thesis, objects are the predictor network's move
probability distribution $bold("p")$ and MCTS' node frequency distribution
$bold(pi)$. Positions
within these distributions are always examined together.
In the implementation used in this thesis, all positions are iterated through
being compared to all following positions. A pair of positions is concordant if
both distributions agree either that $bold("p")_i <
bold("p")_j$ and $bold(pi)_i < bold(pi)_j$ or that $bold("p")_i > bold("p")_j$ 
and $bold(pi)_i > bold(pi)_j$.
Since equal values are also possible, this thesis uses specifially $tau_b$. In 
that case, 
a pair is tied if $bold("p")_i = bold("p")_j$ or $bold(pi)_i = bold(pi)_j$,
both may occur at the same time.
Otherwise, the pair is said to be discordant.
The formula is
$ tau_B = (n_c - n_d) / sqrt((n_0 - n_1) (n_0 - n_2)), $
where
- $n_0$ is the sum of all pairs, $n_0 = n(n-1) \/ 2$,
- $n_1$ is the sum of tied values in $bold("p")$, $n_1 = sum_i t_i (t_i - 1)/2$,
- $t_i$ is the number of tied values containing the $i$-th unique value,
- $n_2$ is the sum of tied values in $bold(pi)$, $n_1 = sum_j u_j (t_j - 1)/2$,
  and 
- $u_j$ is the number of tied values containing the $j$-th unique value.






== Elo
The Elo rating system is used to rank players of games such as Go and Chess. It
considers the likelihood of one player to win over their opponent @elo.
The central formulas are
$ E_A = 1 / (1+10^((R_B-R_A)/400)), $
which calculates the expected result of player $A$ with rating $R_A$ against
player $B$ with rating $R_B$, and
$ R'_A = R_A + K dot (S_A-E_A), $
which updates the ranking of player $A$. $S_A$ is the actual result and can be
$1$ for a win, $0.5$ for a draw, and $0$ for a loss. $K$ scales the rating
adjustment.
Established players are attributed a lower factor to stabilize rankings, whereas 
newer
players have a higher factor to allow rankings to converge more quickly to real
ranking.

Elo points can give an intuition on how likely one player is to win over the
other. For example, player $A$ with $400$ points more
than his opponent $B$ in the Elo system
should win $10$ games out of $11$ because from $R_B-R_A=-400$ follows 
$1/(1+10^(-1))=91%$.






= Previous work
== Pre-deep Learning

=== Before MCTS

Early Go programs were usually rule-based and used pattern
recognition combined with heuristic evaluation functions and search
to find hard-coded patterns and choose actions based on the results.

One such program is "The Many Faces of Go" that was using a large compilation of
rules and an influence function @manyfaces_patterns.  It was competing
successfully in Computer Go
championships in 1998-2002. It was widely considered one of best Go programs of
the time @computer_go. At the time, it reported online online strength
estimates at 8 kyu.
It has since been continuously improved and made to
embrace new technologies until the introduction of Deep Learning @manyfaces_mcts.

A freely consultable open-source program of the time that 
also works based on
rules and pattern-recognition is GnuGo @gnugo. Simplified within the pipeline,
GnuGo first analyses the board
for its state, examines groups, their life-and-death, and their relation to one
another. Next, it generates the moves, and lastly evaluates the moves for its
effect on influence and territory. The move with the highest score is
played.




=== After MCTS

Earlier Go programs were found to perform well in specific parts of the game like
life-and-death problems or local tactical analysis @computer_go. However they
were unable to play a complete game well or even better than amateur players.
Programs of this level of sophistication could not achieve the same level of
success
for Go as for chess, because the computational search for Go is drastically
different. While it is not the only factor, the state-space is much larger on a
large board,
$3^(19 times 19) approx 10^170$ of which $1.2%$ are legal. However, Go on a 
9 #math.times 9-board has a
similar a branching factor to chess and has proved equally as difficult as Go on
a large board. This is due to static position evaluation requiring a large 
amount
of local auxiliary computations. Additionally, in order to find legal moves, the
recent history of the game has to be contained within the state information 
to account
for special rules such as Ko that forbid repetition.

As the typical game is also much longer than in chess, MCTS is a tool better 
suited to explorations because it is capable of a more
dynamical approach @mcts. Furthermore, short-term profit may often be outpaced by an
opponent's stronger tactical play. With the introduction of MCTS into the field
of Computer Go, programs became
improved significantly. 

In Go on a 9 #math.times 9-board, a 5 dan professional player was
beaten by MoGo in 2007; in 2009, a 9 dan professional by Fuego @mogo. In the course of
pure MCTS applied to Go on a 19 #math.times 19-board, various models managed to
defeat high-ranking professional players, albeit with up to 9 handicap stones,
and gained a ranking of 4 dan on online play.





== Deep Learning


=== AlphaGo

The AlphaGo-algorithm is a complex system of CNNs, MCTS, supervised
learning (SL), and RL @alphago. 
SL policy network $p_sigma$ and SL sample network $p_pi$ were trained from a
database of expert-level moves. $p_pi$ was trained to accurately predict human
moves. $p_pi$ was designed to quickly sample actions during the rollout in the
simulation of MCTS. RL policy network $p_rho$ on the other hand is trained to
optimize the outcome of self-play. The RL value network $v^p(s)$ predicts the
outcome using policy $p$.

*Supervised learning*. The first policy network$p_pi(a|s)$ receives as input a
board representation $s$ and gives out movej a probability distribution over all
legal moves $a$. It optimizes the selection of action $a$, given $s$, using
stochastic gradient descent according to $Delta sigma prop frac(delta log
p_(sigma)(a|s), sigma)$. 

*Reinforcement learning*. The second policy network $p_pi(a|s)$ is
architecturally the same, with the same initial weights $rho=pi$ and trained
with policy gradient reinforcement learning. It also outputs a probability
distribution over all legal moves $a$. Self-play is done with a current
and a random previous iteration of the network. The reward function is zero for
all non-terminal time steps and either $+1$ or $-1$ for winning and losing,
respetively. The loss is thus $Delta rho prop frac(delta log p_(rho)(a_t|s_t),
rho)z_t$.#linebreak()
The value function $v^p(s)$ approximates the perfect play $p^*(s)$ using the best
available policy $p$ from $p_rho$ to $v^p(s)=EE[z_t|s_t=s,a_(t...T)~p]$. The
value network $v_theta(s)$ approximates that function. Architecturally,
$v_theta$ is similar to the policy networks but is trained on state-outcome
pairs $(s, z)$ using stochastic gradient descent to minimize the mean-squared
error (MSE) between predicted value $v_theta(s)$ and the actual outcome $z$
$Delta theta prop frac(delta v_theta(s), delta theta)(z-v_(theta)(s))$.

*Search* In the MCTS, each edge $(s,a)$ holds record of an action value
$Q(s,a)$, visit count $N(s,a)$, and prior probability $P(s,a)$. The tree is
traversed by selection of a child at time step $t$ by
$ a_t = op("argmax", limits: #true)_(a)(Q(s_t, a) + u(s_t, a)) $
with a bonus $ u(s,a) prop frac(P(s,a),1+N(s,a)) $ which encourages exploration
by disfavouring much-visited edges.

A leaf node $L$ is processed once by $p_pi$ which outputs the prior
probabilities $P(a|s)=p_(pi)(a|s)$. $v_theta(s_L)$ and $p_sigma(s_L)$#check[] are used to generate
an evaluation $V(s_L)$ of the state of the leaf node weighted by a mixing factor
$lambda$: $ V(s_L)=(1-lambda)v_theta(s_L) + lambda z_L $

At the end of one iteration of search, visited edges are updated. Visits through
all search iterations are counted and mean evaluation calculated to 
$
N(s,a) = sum_(i=1)^(n)1(s,a,i) \
N(s,a) = sum_(i=1)^(n)1(s,a,i) \
Q(s,a) = 1/N(s,a)sum_(i=1)^(n)1(s,a,i)V(s_L^i)
$
where $s_L^i$ is the leaf node $L$ in the $i$th simulation. $1(s, a, i)$ shows
whether that node was visited in the $i$th iteration.

=== AlphaGo Zero
AlphaGo Zero represents a significant improvement over its predecessor,
achieving better performance through a more efficient architecture @alphagozero. By
eliminating the need for human expert data, it masters the game entirely through
self-play.

==== Structure of AlphaGo Zero
Unlike AlphaGo that uses separate policy and value networks, AlphaGo Zero makes
use of a unified DNN, that consists of residual convolutional layers as well as
batch normalisation and rectifier nonlinearities. This network, $f_theta(s)$,
takes as input a board state
$s$ and outputs both move probabilities and state evaluation: $ (bold("p"), v) =
f_theta (s). $
The probability distribution $bold("p")$ is a vector over all allowed moves in
$s$, where $p_a = Pr(a | s)$. The scalar value $v in [-1, 1] approx EE[z,s]$ is the
expected outcome of the game, where $z$ is the outcome of the game. If $z$ is
equal to $1,$ the current player wins. If $z$ is equal to $-1,$ the opponent
wins.

The distribution $bold("p")$ and scalar $v$ guide the following MCTS in the
simulations. To avoid the agent narrowing in on suboptimal solutions,
Dirichlet-noise is added. A weighted Dirichlet distribution $eta, eta tilde
op("Dir")(0.03),$ is added to $bold("p")$ $ P(s,a)=epsilon eta_a + (1-epsilon) 
p_a. $

During each simulation time step, the algorithm selects the action $a_t$ that
maximises PUCT.
After the allotted simulations, MCTS returns a probability distribution based on
visit counts: 
$ bold(pi)(a|s_0) = N(s,a)^(1/tau) / (sum_b N(s_0, b)^(1/tau)), $
where $tau$ is a temperature variable that controls exploration.
From this distribution, an action is sampled.


==== Training of AlphaGo Zero
AlphaGo Zero learns through an iterative self-play loop. The current best
version ($theta$) plays against itself to generate a dataset of $(s_t, pi_t,
z_t)$. The network is updated to minimise the composite loss function
$ l = (z-v)^2 + bold(pi) log bold("p") + c (||theta||)  ^2. $
// - $(z-v)^2$: Mean-squared loss,
// - $bold(pi) log (bold("p"))$: Cross-entropy loss,
// - $c||theta||^2$: L2-regularisation to avoid overfitting.

Furthermore, the fact that Go is rotationally invariable is exploited by
rotating the board and thus generating more valid game positions.



=== AlphaZero
AlphaZero is another iteration on this self-play algorithm @alphazero. While ultimately the
same structure as AlphaGo Zero, the domain-specific optimisation that Go is
rotationally invariable is removed which reduces the amount of data of data
available for this game.

AlphaZero managed to beat state-of-the-art models in chess (Stockfish), shogi
(Elmo), and Go (AlphaGo Zero).

=== The Alpha-Models
There are multiple named versions of AlphaGo, each with their own achievements.
AlphaGo Fan, which was the program to win against a human professional on a $9
times 9$ board, won $5$-nil @alphago. AlphaGo Lee Sedol won against Lee Sedol with a
record
of $4-1$. The last iteration, AlphaGo Master, won against top human 
professionals in online games with a record of $60-0$ alphagozero. When these models were 
compared to AlphaGo Zero, their
Elo ratings were $3,144$, $3,739$, and $4,858$, respectively. AlphaGo Zero
received a rating of $5,158$ alphagozero.


=== MuZero
MuZero is a generalisation of the Alpha-family @muzero. While previous models required a
working model of the environment, MuZero is capable of learning about the
environment through interaction with the environment. While also achieving
similar results on traditional games such as Go and chess, it is also capable of
learning to play real-time games like Atari. In all of these domains, it was
capable of surpassing state-of-the-art models and therefore top human
professionals.

=== Gumbel AlphaZero
Google DeepMind's successor model, Gumbel AlphaZero, breaks from traditional
MCTS using UCB or variants, and
instead makes use of other policy improvement strategies @gumbelzero.
One such strategy is Sequential Halving.

=== KataGo
KataGo represents a significant step to the wider Computer Go community @katago. 
While
similarly strong models such as FineArt exist, KataGo is one the few open-source 
models.
Improving on the architecture and
process of AlphaZero, KataGo introduces and publicly explains several
domain-dependent and -independent additions to improve efficiency,
flexibility, and utility for human analysis.

Some of these features include:
- Auxiliary Policy Targets: In addition to simply predicting the best move for
  the current board position, KataGo also predicts the opponent's move.
- Playout Cap Randomisation: Most board positions are searched with a low number
  of simulations and only used to train the value head. Long playouts are then
  used for policy training.
- Blocking Overplay: Forbidding playing in a certain region after a number of
  moves contributes in efficiency, albeit little in regard to performance.
- Auxiliary Ownership and Score Targets: The network also predicts to whom an
  intersection belongs as well as a estimations of the point difference at the
  end of the game.



=== Further research 
// - Monte Carlo Graph Search (MCGS): A notable advancement where the search tree
//   is generalized into a Directed Acyclic Graph (DAG). This allows the AI to
//   recognize transpositions—different sequences of moves that lead to the
//   identical board state—significantly reducing redundant computations on the 9x9
//   board.
// - Terminal Solvers: Since 9x9 Go is a smaller domain, some implementations
//   integrate "mini-max" style terminal solvers within the MCTS leaves. If a
//   branch can be proven as a win or loss through exhaustive search, the result is
//   backpropagated immediately, pruning the tree.
// - Warm-Start MCTS: Researchers have experimented with using classical heuristics
//   (like RAVE) to "warm-start" the MCTS during the early stages of AlphaZero
//   self-play training, mitigating the high failure rate of agents starting with
//   purely random weights.

==== Dynamic MCTS
Forming a basis for this thesis, Lan et al. introduced
estimations of uncertainty at intervals during training, to determine whether
continued search is necessary @d_mcts. As MCTS finds the optimal move after 1
simulation 62% of the time, and most positions require far less than the
maximal number for the same, it is permissible to explore fewer situations. 
Thus, if there is founded certainty that the best
move has been found, search should terminate.

= Methodology

== Reasoning 9 #math.times 9 vs. 19 #math.times 19
A $9 times 9$ board has a state-space complexity of $3^81 approx 4 times 10^38$,
of which $23.43% approx 1.04 * 10 ^ 38$ @combinatorics
are legal. 
In contrast, a $19 times 19$ board has $3*(19 times 19) approx 1.74 * 10^172$ 
possible positions and $2.082 times 10^170$
 legal positions . Thus,
in order to gain comprehensive results within the hardware and temporal limits
of this thesis, the board size is restricted to $9 times 9$.


== Choosing AlphaGo Zero Over Alternatives
The basic AlphaZero structure is used as the baseline in this work for reasons
of clarity and experimental control.
Although models such as KataGo achieves state-of-the-art performance @katago, 
it does so by
incorporating a wide range of engineering optimisations, training heuristics,
and system-level improvements. As a result, isolating the effect of
modifications within such a system can be difficult, since performance gains may
arise from interactions with existing components rather than the modification
itself. 

Similarly, improvements 


To achieve this level, KataGo is highly optimised 
using a multitude of methods,
including those above @katago. Introducing a new heuristic, 
it is difficult to determine
whether resulting performance is due to the heuristic 
itself or its interaction
with one or more of KataGo's many existing optimisations. 
Furthermore, the
codebase includes and is highly optimised for a variety of use-cases. This
includes training on multiple machines, the optimisations explained above, and
generalisability to multiple board sizes. This combines to a complex 
codebase
that introduces unnecessary complications into the development process. 

Despite the relative successes of the Gumbel models compared to their PUCT-based
predecessors @gumbelzero, the PUCT-based models remain the most widely employed
approach in the popular Go models @katago.




== Environment (Training server, implementation)
The primary research tool for this study is OpenSpiel, an open-source framework
developed by Google DeepMind to simplify RL resarch in games @openspiel. 
It provides a robust, community-validated 
implementation of the 
AlphaZero algorithm and native
support for the game Go.

OpenSpiel's AlphaZero implementation is entirely written in C++. It uses
OpenSpiel's custom MCTS implementation and Meta's ML-library LibTorch. The
9 #math.times 9 Go environment in OpenSpiel follows standard Tromp-P Taylor 
rules.


=== Computational Resources: University HPC Cluster

Due to the high computational cost of self-play reinforcement learning, all
training and evaluation experiments were conducted on the University’s
High-Performance Computing (HPC) Cluster.
==== Hardware Configuration

The cluster provides a distributed environment optimized for deep learning. The specific resources allocated for this project include:

- Compute Nodes: Training was distributed across [X] nodes, each equipped with
  [Y] CPU cores (e.g., AMD EPYC or Intel Xeon) to handle the parallel MCTS
  simulations.

- Accelerators: Neural network training and inference during self-play were
  accelerated using NVIDIA [Model,e.g.,A100/V100] GPUs, providing the necessary
  TFLOPS for high-throughput batch processing.

- Memory: Each node provided [Z] GB of RAM to maintain large MCTS search trees
  and experience replay buffers.


== Heuristics
The heuristics suggested here are based on the idea, that the prior is able to
epxress an inherent certainty that can be leveraged to adjust
the amount of simulation needed to generate a successful training sequence while
lowering the computational efforts.



=== Entropy of Likeliest $k$ Actions
The goal for this heuristic is to calculate the entropy of the $k$ highest-rated
moves of the predictor's move probability distribution and adjust the amount of
simulations accordingly.

Entropy is by itself a measure of uncertainty for a distribution of
probabilities. The use of the entropy is therefore an apparent possible solution
to the goal of this thesis. Furthermore, using the $2$ likeliest options of a
probability
distribution is a common approach to gather a measure of certainty of that
distribution. 

The important formulas are
$ H_"norm" = frac(H("Top"k),ln(k)), $
$ n_"new" = n_"base" dot frac(2, 1+e^(-s(H_"norm"-s p))) $ <ent_eq>
where 
- $H("Top"k)$ is the entropy of the $k$ highest ranked moves of $pi$ that are
  sorted descendingly in $"Top"k$.
- $H_"norm"$ is the result of re-normalising the entropy of these moves to
  within the range $[0,1]$,
- $n_"new"$ is the applied number of simulations, 
- $n_"base"$ is the baseline number of simulations,
- $s$ is the steepness of the graph, and
- $s p$ is the position of the inflection point on the $x$-axis.

@ent_eq, represented in @log_graph, is a logistic function. 
The formula here will continue to be used with $s = 8$ and $s p = 0.5.$
The graph is maximised at $frac(2,
1+e^(-8(1-0.5))) approx 1.964$ 
and, because $H$ is
normalised, it is minimised at $frac(2, 1+e^(-8(0-0.5))) approx 0.036$.
This should allow the entropy of the $k$ highest-rated to transition
fluidly around the inflection point at $0.5$. 

#figure(
  plot(
    xmin: -0.5, xmax: 1.5,
    ymin: 0, ymax: 2,
    width: 3, height: 3,
    xlabel: $x$,
    ylabel: $y$,
    show-grid: true,
    (fn: x => (2 / (1 + calc.exp(-8 * (x - (1/2))))), 
      stroke: gray + 1.5pt,
      label: $frac(2, 1+e^(-8(x-0.5)))$,
      label-pos: 0.5,
      label-side: "below-right",
    ),
  ),
  caption: [Logistical uncertainty function]
) <log_graph>

Effort for this heuristic should be near negligible. The algorithmic complexity
of finding the highest-sorted  $"O"(|A| dot log k)$, with $|A|$ as the space of
all actions. There also is the additional cost of calculating the entropy of
$"Top"k$.

Making use of more values of that distribution should also provide
a clearer estimation of certainty, differences are discussed in a later section.







=== Comparison of High And Low Ranking Moves
This heuristic measures the disparity between the probability densities of the
$k$ highest-rated
moves and the $A-k$ lowest-rated moves. Using this distance,
the number of simulations is adjusted.

The above heuristic has a strong focus on relatively few high-rated moves
compared to the overall space of possible moves. This increases vulnerablity to
overconfidence where it is not warranted. That is especially the case when a
single over is disproportionately well-rated. Therefore, one solution to this
problem can be
a more global consideration of the move probability space.

$ d = sum_(a in "Top"k)pi(a) - sum_(a in A without "Top"k)pi(a), $
$ n_"new" = n_"base" dot (2/), $ <den_eq>
where
- $pi(a)$ is the probability of $a$ in $pi$,
- $"Top"k$ is the array of the highest-rated $k$ actions,
- $A$ is the space of all possible actions.

@den_eq is the same as @ent_eq with the entropy exchanged for the difference of
the probability densities.



This solution should be able to help mitigate the inequal consideration of moves
from the first heuristic. Computational effort consists of the sorting in $O(n
log k)$ and the addition. Therefore the effort should be about as much as for
the first heuristic.

Differences in $k$ here will also be discussed in a later section.











=== Auxiliary Head Estimating Uncertainty 
Lan et al. introduced supplementary networks to estimate certainty and stop
searching when reaching a certain threshold. However,
as merging networks for predicting value and policy has proved successful
previously, 
enabling the network to predict its own prediction-search disagreement should also turn
out beneficial. 
The predictor network $f$ on board position $s$ will return
$ f(s)=(bold("p"),v, u), $ where 
$bold("p")$ is the move probability distribution, $v$ the evaluation, and $u$
the uncertainty estimation. 
The number of simulations is adjusted according to
the formula
$ n_"new" = n_"baseline" dot exp(u). $
This means, that searching more thoroughly correlates with higher uncertainty
while a lower number of simulations correlates with less uncertainty. The
exponential function allows both to increase and decrease the number of
simulations. $n_"new"$ also is limited to a maximal number to
stop the search from going unendingly long.



The loss will be calculated using the expression
$ l_"all" = l_"az" + c dot (u - lambda dot tau(bold("p"), pi))^2, $
where
- $l_"az"$ is the error signal used by AlphaZero considering $(bold("p"), 
sigma, v, theta))$,
- $c$ is a weighting constant for MSE,
- $tau(bold("p"), pi)$ is the KRCC of board state $s$,
- $lambda$ is a scaling constant for the KRCC, and
- $pi$ is the distribution found by MCTS.
In this context $tau(bold("p"), pi)$ measures the similarity between the ranked
move
distribution estimated by the prior and the ranked move distribution determined
by MCTS.



This heuristic should be capable of reducing the average simulation numbers by
predicting how much move estimations change during MCTS in different positions.
However, especially the process can be very time-intensive in the beginning of a
single game when more moves are available and the calculation of KRCC requires
more effort.


While the idea is promising, a glaring problem with this approach is the
computational cost of calculating the KRCC for the two distributions. One
solution is to similarly to the above heuristics consider only the highest $k$
actions. This is also looked at in the following sections.




=== Random
Following the example of Wu et al., a uniformly chosen number from $n in [1,
#max_number]$ will be used as the number of playouts for MCTS
in order to investigate in comparison whether these
strategies actually fulfill their purpose
and have an active part in lowering computational effort. If this
performs equally well as the strategies suggested above and assuming that they
all perform similarly well to the base line model, this would
suggest that these strategies constitute unnecessary computational effort.

== Evaluation
After the models are trained, they play against each other #fill[certain amount
of games] to evaluate playing strength. To further evaluate ability, the
BayesElo-algorithm will be
used. #fill[or #(math.alpha)-Rank] The models also record the number of
simulations executed from MCTS during training as well as test-play to enable
comparisons between computational effort spent.
As a method of comparing the efficiency of models, the following formula may
give insights into the differences:
$ S E = (Delta "Elo") / (Delta "Simulations") $

= Experiments
== Tuning Hyperparameters
For each heuristic, the size of the window of consideration may play
a significant role 
in the performance of the model and effort of the heuristic. Therefore, to
find a balance between performance and effort, $k in {2,5,10}$ are trained for
each heuristic and compared to performance.

Similarly, limiting the window of consideration to the most likely moves for the
last heuristic may also 

For the first three heuristics, $k$ may play a huge role in accuracy and effort.
Therefore, to find a good $k$, these approaches are first run with $a in
{2,5,10}$. The models will be given 12 hours to train and are conclusively
compared. The hyperparameter with the best performance will be continued to be
used throughout the other experiments.

== Simple Usage

// == Using Heuristics in Training And Play
//
// == Using Heuristics in Training
//
// == Using Heuristics in Play

== Forced Maximal Number Simulations
Wu et al. noticed that using fewer simulations is permissible as long as there 
are correcting playouts of sufficient length to correct the gradient of 
learning. However, KataGo unilaterally cuts of exploration of a board position
after the lowered number of simulations during most board searches. The
heuristics proposed here aim at precisely that point at which further
exploration of the state
becomes less useful than exploring the next state.

== Pruning Superfluous Child Nodes
Previous results show improved performance by pruning unnecessary nodes so that
nodes of a higher probability can be more rigorously tested. This might prove
especially useful in the use cases of these heuristics that put a lower limit on
available simulations.

== Warm-up


= Discussion

= Conclusion




#pagebreak()
#bibliography("text/sources.yml", style: "ieee")
