turochamp:
  type: chapter
  title: "Digital Computers Applied to Games"
  author: Turing, Alan M.
  parent:
    type: book
    title: "Faster Than Thought: A Symposium on Digital Computing Machines"
    editor: Bowden, B. V.
    publisher: Pitman
    date: 1953
  pages: 286-310

mechanical_turk:
  type: book
  title: "Inanimate Reason; or, a Circumstantial Account of That Astonishing Piece of Mechanism, M. de Kempelen's Chess-Player"
  author: von Windisch, K. G.
  publisher: S. Bladon
  date: 1784
  location: London

kasparov_v_deep_blue:
  type: web
  title: "Deep Blue"
  author: "IBM"
  url: "https://www.ibm.com/history/deep-blue"

stockfish_blog:
  type: web
  title: "Stockfish Blog"
  author: "IBM"
  url: "https://stockfishchess.org/blog/2026/stockfish-18/"
  date: 2026-01-31

sedol_v_alphago:
  type: web
  title: "AlphaGo"
  author: "DeepMind"
  url: "https://deepmind.google/research/alphago/"

alphago:
    type: Article
    title: Mastering the game of Go with deep neural networks and tree search
    author:
      - Silver, D.
      - Huang, A.
      - Maddison, C.
      - Guez, Arthur
      - Sifre, Laurent
      - van den Driessche, George
      - Schrittwieser, Julian
      - Antonoglou, Ioannis
      - Panneershelvam, Veda
      - Lanctot, Marc
      - Dieleman, Sander
      - Grewe, Dominik
      - Nham, John
      - Kalchbrenner, Nal
      - Sutskever, Ilya
      - Lillicrap, Timothy
      - Leach, Madeleine
      - Kavukcuoglu, Koray
      - Graepel, Thore
      - Hassabis, Demis  
    serial-number:
      doi: "10.1038/nature16961"
    page-range: 484-489
    date: 2016-01-27
    parent:
        type: Periodical
        title: Nature
        volume: 529

alphagozero:
  type: Article
  title: Mastering the game of Go without human knowledge
  author:
    - Silver, David
    - Schrittwieser, Julian
    - Simonyan, Karen
    - Antonoglou, Ioannis
    - Huang ,Aja
    - Guez, Arthur
    - Hubert, Thomas
    - Baker, Lucas
    - Lai, Matthew
    - Bolton, Adrian
    - Chen, Yutian
    - Lillicrap, Timothy
    - Hui, Fan
    - Sifre, Laurent
    - van den Driessche, George
    - Graepel, Thore
    - Hassabis, Demis
  serial-number:
    doi: "10.1038/nature24270"
  parent:
    type: Periodical
    title: Nature
    volume: 550
  page-range: 354-359
  date: 2017-10-19

alphazero:
  type: Article
  title: Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm
  author:
    - Silver, David 
    - Hubert, Thomas 
    - Schrittwieser, Julian 
    - Antonoglou, Ioannis 
    - Lai, Matthew
    - Guez, Arthur 
    - Lanctot, Marc 
    - Sifre, Laurent 
    - Kumaran, Dharshan 
    - Graepel, Thore 
    - Lillicrap, Timothy 
    - Simonyan, Karen 
    - Hassabis, Demis 
  serial-number:
    doi: 10.48550/arXiv.1712.01815

muzero:
  type: Article
  title: Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model
  author:
    - Schrittwieser, Julian
    - Antonoglou, Ioannis
    - Hubert, Thomas
    - Simonyan, Karen
    - Sifre, Laurent
    - Schmitt, Simon
    - Guez, Arthur
    - Lockhart, Edward
    - Hassabis, Demis
    - Graepel, Thore
    - Lillicrap, Timothy
    - Silver, David
  serial-number:
    doi: 10.48550/arXiv.1911.08265

gumbelzero:
  type: Article
  title: Policy Improvement by Planning with Gumbel
  author:
    - Danihelka, Ivo
    - Guez, Arthur
    - Schrittwieser, Julian
    - Silver, David
  parent:
    type: conference
    title: International Conference on Learning Representations
  date: 2022

katago:
  type: Article
  title: Accelerating Self-Play Learning in Go
  author: Wu, David J.
  date: 2020-11-10
  serial-number:
    doi: 10.48550/arXiv.1902.10565

aireport:
  type: report
  title: "Artificial Intelligence Index Report 2025"
  author: "AI Index Steering Committee"
  publisher: "Stanford Institute for Human-Centered AI (HAI)"
  date: 2025-04
  location: "Stanford, CA"
  url: "https://hai.stanford.edu/ai-index/2025-ai-index-report"

rl_intro:
  type: book
  title: "Reinforcement Learning: An Introduction"
  author:
    - Sutton, Richard S.
    - Barto, Andrew G.
  date: 2018
  edition: "2nd"
  publisher: "MIT Press"
  address: "Cambridge, MA"
  url: "http://incompleteideas.net/book/the-book-2nd.html"  

perc_rosenblatt:
  type: Article
  title: "The Perceptron: A Probabilistic Model for Information Storage and Organization in the Brain"
  author: Rosenblatt, Frank
  serial-number:
    doi: 10.1037/h0042519
  date: 1958-11-01
  parent:
    type: Periodical
    title: "Psychological Review"
    volume: 65
    issue: 5

resnet:
  type: Article
  title: "Deep Residual Learning for Image Recognition"
  author: 
    - He, Kaiming
    - Zhang, Xiangyu
    - Ren, Shaoqing
    - Sun, Jian
  date: 2016-06
  parent:
    type: Proceedings
    title: "2016 IEEE Conference on Computer Vision and Pattern Recognition"
    location: Las Vegas, NV, USA
  page-range: 770-778
  serial-number: 
    doi: 10.1109/CVPR.2016.90

backprop:
  type: Article
  title: Learning representations by back-propagating errors
  author:
    - Rumelhart, David E.
    - Hinton, Geoffrey E.
    - Williams, Ronald J.
  serial-number:
    doi: 10.1038/323533a0
  date: 1986-10
  parent:
    type: Periodical
    title: Nature
    volume: 323
  page-range: 533-536

cnn:
  type: Article
  title: Gradient-based learning applied to document recognition,
  author:
    - Lecun, Y. 
    - Bottou, L.  
    - Bengio, Y. 
    - Haffner, P.
  serial-number:
    doi: 10.1109/5.726791
  date: 1998-11
  parent:
    type: Proceedings
    title: "Proceedings of the IEEE"
    volume: 86
    issue: 11
  page-range: 2278-2324

uct:
  type: Article
  title: Bandit Based Monte-Carlo Planning
  author:
    - Kocsis, L.
    - Szepesvári, C.
  editor: 
    - Fürnkranz, J. 
    - Scheffer, T. 
    - Spiliopoulou, M.
  serial-number:
    doi: 10.1007/11871842_29
  date: 2006
  parent:
    type: Book
    title: "Machine Learning: ECML 2006"
    parent: 
      type: Periodical
      title: Lecture Notes In Computer Science
      volume: 4212
      publisher: Springer
      location: "Berlin, Heidelberg"

rankcorrelation:
  type: chapter
  title: Tied Ranks
  author: 
    - Kendall, Maurice G.
    - Gibbons, Jean D.
  serial-number:
    isbn: 0195208374
  parent:
    type: Book
    title: Rank Correlation Methods
    date: 1990
    edition: 5
  page-range: 40-60

elo:
  type: book
  title: The Rating of Chessplayers, Past & Present
  author: Elo, Arpad E.
  serial-number:
    isbn: 9780923891275
  date: 1978
  publisher: Ishi Press International
  url: "https://archive.org/details/ratingofchesspla0000eloa"
  edition: reprint
  
gnugo:
  type: repository
  title: GnuGo
  url: https://www.gnu.org/software/gnugo/devel.html

manyfaces_patterns:
  type: Article
  title: ManyFaces
  url: https://www.cgl.ucsf.edu/go/Programs/ManyFaces.html

manyfaces_mcts:
  type: Article
  title: Monte Carlo Tree Search in Go
  url: https://webdocs.cs.ualberta.ca/~mmueller/ps/2013/2013-gochapter-preprint.pdf

computer_go:
  type: Article
  title: Computer Go
  author: Martin Müller
  serial-number:
    doi: 10.1016/S0004-3702(01)00121-7
  date: 2002-01
  parent:
    type: Periodical
    title: Artificial Intelligence
    volume: 134
    issue: 1-2
  page-range: 145-179

mcts:
  type: Article
  title: Efficient Selectivity and Backup Operators in Monte-Carlo Tree Search
  author: Rémi Coulom
  serial-number:
    doi: 10.1007/978-3-540-75538-8_7
  date: 2006-05
  parent:
    type: conference
    title: Computers and Games
    location: Turin, Italy
    publisher: Springer, Berlin, Heidelberg
  page-range: 72-83

mogo:
  type: Article
  title: "The Grand Challenge of Computer Go: Monte Carlo Tree Search and Extensions"
  author:
    - Gelly, Sylvain
    - Kocsis, Levente
    - Silver, David
    - Szepesvári, Csaba
  serial-number:
    doi: 10.1145/2093548.2093574
  date: 2012-03
  parent:
    type: Periodical
    volume: 55
    issue: 3
  page-range: 106-113

d_mcts:
  type: Article
  title: "Learning to Stop: Dynamic Simulation Monte-Carlo Tree Search"
  author:
    - Lan, Li-Cheng
    - Tsai, Meng-Yu
    - Wu, Ti-Rong
    - Wu, I-Chen
    - Hsieh, Cho-Jui
  serial-number:
    doi: 10.48550/arXiv.2012.07910

combinatorics:
  type: Article
  title: "Combinatorics of Go"
  author:
    - Tromp, John
    - Farnebäck, Gunnar
  editor:
    - van den Herik, H. Jaap
    - Ciancarini, Paolo
    - Donkers, H. H. L. M.
  serial-number: 
    doi: 10.1007/978-3-540-75538-8_8
  parent:
    type: conference
    title: Computers and Games
    date: 2006
    publisher: Springer Berlin, Heidelberg
    location: Berlin, Heidelberg
    serial-number:
      isbn: 978-3-540-75538-8
  page-range: 84-99

openspiel:
  type: Article
  title: "OpenSpiel: A Framework for Reinforcement Learning in Games"
  serial-number:
    doi: 10.48550/arXiv.1908.09453
    arxiv: abs/1908.09453
  author:
    - Lanctot, Marc 
    - Lockhart, Edward 
    - Lespiau, Jean-Baptiste 
    - Zambaldi, Vinicius 
    - Upadhyay, Satyaki 
    - Pérolat, Julien 
    - Srinivasan, Sriram 
    - Timbers, Finbarr 
    - Tuyls, Karl 
    - Omidshafiei, Shayegan 
    - Hennes, Daniel 
    - Morrill, Dustin 
    - Muller, Paul 
    - Ewalds, Timo 
    - Faulkner, Ryan 
    - Kramár, János 
    - De Vylder, Bart 
    - Saeta, Brennan 
    - Bradbury, James 
    - Ding, David 
    - Borgeaud, Sebastian 
    - Lai, Matthew 
    - Schrittwieser, Julian 
    - Anthony, Thomas 
    - Hughes, Edward 
    - Danihelka, Ivo 
    - Ryan-Davis, Jonah 
  date: 2019
  parent: 
    type: Periodical
    title: CoRR
    volume: abs/1908.09453
  url: http://arxiv.org/abs/1908.09453

leelazero:
  type: repository
  title: "Leela-zero"

alpha_hu:
  type: repository
  title: "Alpha Zero: A PyTorch implementation of DeepMind's AlphaZero agent"
  author: Michael Hu
  url: https://github.com/michaelnny/alpha_zero
  version: 2.0.0
  year: 2022
